apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snappass
    name: snappass-nginx
    tier: frontend
  name: snappass-nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: snappass-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snappass-nginx
    spec:
      automountServiceAccountToken: true
      containers:
      - image: shanmukha511/splunk-hec-private:nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 443
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: snappass
    name: snappass-nginx
    tier: frontend
  name: snappass-nginx
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: snappass-nginx
  type: LoadBalancer

