apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snappass
    name: snappass
    tier: backend
  name: snappass
  namespace: default
spec:
  selector:
    matchLabels:
      app: snappass
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snappass
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: REDIS_HOST
          value: snappass-redis
        image: shanmukha511/splunk-hec-private:snap
        imagePullPolicy: IfNotPresent
        name: snap
        ports:
        - containerPort: 5000
          protocol: TCP	  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: snappass
    name: snappass
    tier: backend
  name: snappass
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: snappass
  type: ClusterIP